
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 163
#define YY_END_OF_BUFFER 164
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[291] =
    {   0,
        0,    0,  164,  162,  163,  160,  161,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
       52,  162,  162,   64,   65,   62,  162,  162,  162,  162,
      151,  162,  162,  155,  154,  103,   68,  109,  107,  111,
      113,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,   47,   48,   54,   49,   50,   42,   43,   44,
       46,   53,   45,   61,   55,  130,  146,  147,  148,   88,
       90,   91,   75,   69,   85,   87,   81,   82,   77,   86,

      135,   95,   93,  156,  162,  162,  144,  145,  159,  162,
      149,  150,  162,  138,  133,  142,  110,  112,  106,  108,
      104,  105,  114,  115,  162,  162,  162,  128,  153,  122,
      162,   66,   63,  117,   56,   57,   58,   59,   60,   51,
       99,  102,  101,  162,   11,   36,   14,   12,   35,   13,
       15,   38,   23,   17,   22,   19,   21,   20,   32,   34,
      158,   33,   31,   39,   37,  152,  125,  100,   27,   28,
       30,  131,  132,   29,   24,   18,   26,  157,   25,  126,
       70,   72,   84,   71,   92,   94,   79,   78,   83,   89,
       98,   76,   16,   40,   41,  139,  116,  123,  136,   97,

       74,   73,   80,   96,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  124,  141,  162,  134,  127,  121,
      120,   67,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,    3,  129,  118,  143,
      162,    1,  162,    2,  162,  140,  137,  162,  162,  162,
        6,    5,  162,  162,  162,  162,  162,  162,  162,  162,
        4,    9,  162,  162,  162,  162,  162,  162,  162,   10,
      162,  162,  162,  162,  162,  162,    8,    7,  119,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,    1,    1,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
       62,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   64,   65,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[293] =
    {   0,
        0,    3,  250,    0,  399,    0,    0,    0,  213,    0,
      188,    0,  190,    2,    0,    0,    0,    0,    4,   59,
        0,  182,  181,    0,    0,    0,  180,  179,  177,  176,
        0,  175,  174,    0,    0,    0,    0,    7,    0,    0,
        0,    5,   83,   25,  106,   70,  108,   44,  164,    2,
      174,  203,  176,  260,  223,  224,  207,  187,  298,  339,
       21,  139,  167,  166,  165,  164,  162,  161,  160,  159,
      158,  180,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  151,  150,    0,    0,    0,  149,
        0,    0,  149,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,  148,  147,    0,    0,    0,
      142,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  141,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  171,  133,  132,  131,  169,  141,  151,
      139,  180,  125,  120,    0,    0,  111,    0,    0,    0,
        0,    0,  108,  133,  151,  150,  147,  114,  155,  142,
      153,  144,  141,  139,  138,  121,    0,    0,    0,    0,
       92,    0,   43,    0,   90,    0,    0,  102,  131,   91,
       81,   80,  104,   75,   98,  117,   89,   83,  110,   69,
        0,    0,  115,  114,   98,  101,   56,   40,   39,    0,
       38,   37,    5,   16,    5,    2,    0,    0,    0,  399,
      396,    0

    } ;

static const flex_int16_t yy_def[293] =
    {   0,
      291,  291,  290,  292,  290,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,    0,
      290,  290

    } ;

static const flex_int16_t yy_nxt[465] =
    {   0,
       10,    5,    6,    7,    5,    6,    7,  290,   11,  128,
       27,  290,   31,   39,   40,   41,   33,   32,  290,   12,
       28,  289,   29,   34,  288,   37,   13,   35,   14,   30,
       15,  196,   16,   17,   18,  287,  197,   38,   36,  129,
       86,  290,   87,   88,   89,  290,   19,  290,  130,  198,
      199,   22,  290,   23,  290,   73,   74,  290,   24,   25,
      113,  114,    8,  286,    9,    8,   75,    9,   42,   43,
       71,   72,   90,   91,   92,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,  261,  262,   54,   55,   56,
       57,  219,  115,  220,   58,  285,  284,   59,   60,   61,

       62,   76,  283,  282,   77,   78,   79,   80,   81,  104,
       82,   83,   84,   85,   93,  109,   94,  105,  106,  281,
      280,  279,  110,  278,  277,  107,  108,  276,  275,  274,
       95,   96,   97,   98,  111,  273,  272,  271,  270,  269,
       99,  100,  268,  267,  112,  200,  101,  201,  202,  266,
      203,  204,  265,  264,  263,  260,  259,  258,  257,  102,
      256,  255,  254,  253,  252,  251,  250,  103,  116,  249,
      248,  247,  246,  245,  117,  118,  119,  120,  244,  121,
      122,  123,  124,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,

      226,  225,  125,  126,  224,  223,  127,  132,  133,  222,
      221,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  134,  208,  207,  206,  205,  168,  167,  166,  165,
      144,  131,  135,  136,  137,  138,  139,   70,   69,   68,
       67,  140,   66,   65,   64,   63,   26,   21,   20,  290,
      290,  290,  290,  290,  290,  290,  290,  141,  290,  290,
      142,  290,  290,  143,  145,  146,  147,  148,  149,  290,
      150,  151,  290,  290,  152,  153,  290,  154,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  155,  156,  157,
      158,  159,  290,  290,  290,  160,  161,  290,  162,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  163,  290,  290,  290,  290,  164,  169,  290,
      170,  290,  171,  290,  290,  172,  290,  290,  290,  290,
      290,  173,  290,  290,  174,  290,  175,  290,  290,  290,
      290,  176,  290,  177,  178,  179,  180,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      181,  182,  183,  184,  290,  290,  185,  290,  290,  186,
      290,  290,  290,  187,  290,  290,  290,  290,  290,  290,
      290,  188,  189,  190,  191,  192,  290,  290,  290,  193,
      290,  290,  290,  290,  194,  195,    4,    4,    3,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290
    } ;

static const flex_int16_t yy_chk[465] =
    {   0,
      292,    1,    1,    1,    2,    2,    2,    0,    8,   50,
       14,    0,   16,   19,   19,   19,   17,   16,    0,    8,
       14,  286,   15,   17,  285,   18,    8,   17,    8,   15,
        8,   61,    8,    8,    8,  284,   61,   18,   17,   50,
       44,    0,   44,   44,   44,    0,    8,    0,   50,   61,
       61,   12,    0,   12,    0,   42,   42,    0,   12,   12,
       48,   48,    1,  283,    1,    2,   42,    2,   20,   20,
       38,   38,   44,   44,   44,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,  253,  253,   20,   20,   20,
       20,  125,   48,  125,   20,  282,  281,   20,   20,   20,

       20,   43,  279,  278,   43,   43,   43,   43,   43,   46,
       43,   43,   43,   43,   45,   47,   45,   46,   46,  277,
      276,  275,   47,  274,  273,   46,   46,  270,  269,  268,
       45,   45,   45,   45,   47,  267,  266,  265,  264,  263,
       45,   45,  262,  261,   47,   62,   45,   62,   62,  260,
       62,   62,  259,  258,  255,  251,  246,  245,  244,   45,
      243,  242,  241,  240,  239,  238,  237,   45,   49,  236,
      235,  234,  233,  227,   49,   49,   49,   49,  224,   49,
       49,   49,   49,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,

      206,  205,   49,   49,  144,  131,   49,   52,   52,  127,
      126,  113,  110,  106,  105,   72,   71,   70,   69,   68,
       67,   52,   66,   65,   64,   63,   58,   57,   56,   55,
       53,   51,   52,   52,   52,   52,   52,   33,   32,   30,
       29,   52,   28,   27,   23,   22,   13,   11,    9,    3,
        0,    0,    0,    0,    0,    0,    0,   52,    0,    0,
       52,    0,    0,   52,   54,   54,   54,   54,   54,    0,
       54,   54,    0,    0,   54,   54,    0,   54,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   54,   54,   54,
       54,   54,    0,    0,    0,   54,   54,    0,   54,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   54,    0,    0,    0,    0,   54,   59,    0,
       59,    0,   59,    0,    0,   59,    0,    0,    0,    0,
        0,   59,    0,    0,   59,    0,   59,    0,    0,    0,
        0,   59,    0,   59,   59,   59,   60,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       60,   60,   60,   60,    0,    0,   60,    0,    0,   60,
        0,    0,    0,   60,    0,    0,    0,    0,    0,    0,
        0,   60,   60,   60,   60,   60,    0,    0,    0,   60,
        0,    0,    0,    0,   60,   60,  291,  291,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "emoji.l"
#line 2 "emoji.l"
#include <string.h>
#include"y.tab.h"
#line 644 "lex.yy.c"
#line 645 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 6 "emoji.l"

#line 864 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 399 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "emoji.l"
{yylval.string=strdup("me"); return NOUN;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "emoji.l"
{yylval.string=strdup("we"); return NOUN;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "emoji.l"
{yylval.string=strdup("you"); return NOUN;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "emoji.l"
{yylval.string=strdup("them"); return NOUN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "emoji.l"
{yylval.string=strdup("she"); return NOUN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "emoji.l"
{yylval.string=strdup("he"); return NOUN;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 13 "emoji.l"
{yylval.string=strdup("her"); return NOUN;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 14 "emoji.l"
{yylval.string=strdup("his"); return NOUN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "emoji.l"
{yylval.string=strdup("slow"); return NOUN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "emoji.l"
{yylval.string=strdup("fast"); return NOUN;}
	YY_BREAK
case 11:
#line 20 "emoji.l"
case 12:
YY_RULE_SETUP
#line 20 "emoji.l"
{yylval.string=strdup("smile"); return NOUN;} 
	YY_BREAK
case 13:
#line 22 "emoji.l"
case 14:
YY_RULE_SETUP
#line 22 "emoji.l"
{yylval.string=strdup("lmao"); return NOUN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 "emoji.l"
{yylval.string=strdup("angel"); return NOUN;}
	YY_BREAK
case 16:
#line 25 "emoji.l"
case 17:
YY_RULE_SETUP
#line 25 "emoji.l"
{yylval.string=strdup("inlove"); return NOUN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 26 "emoji.l"
{yylval.string=strdup("amazed"); return NOUN;}
	YY_BREAK
case 19:
#line 28 "emoji.l"
case 20:
#line 29 "emoji.l"
case 21:
#line 30 "emoji.l"
case 22:
YY_RULE_SETUP
#line 30 "emoji.l"
{yylval.string=strdup("kiss"); return VERB;}
	YY_BREAK
case 23:
#line 32 "emoji.l"
case 24:
YY_RULE_SETUP
#line 32 "emoji.l"
{yylval.string=strdup("delicious"); return NOUN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 33 "emoji.l"
{yylval.string=strdup("oops"); return NOUN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 34 "emoji.l"
{yylval.string=strdup("shhh"); return NOUN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 35 "emoji.l"
{yylval.string=strdup("don't say a word"); return NOUN;}
	YY_BREAK
case 28:
#line 37 "emoji.l"
case 29:
YY_RULE_SETUP
#line 37 "emoji.l"
{yylval.string=strdup("cowboy"); return NOUN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 38 "emoji.l"
{yylval.string=strdup("mmm"); return NOUN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 39 "emoji.l"
{yylval.string=strdup("totally"); return NOUN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 40 "emoji.l"
{yylval.string=strdup("lick"); return VERB;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 41 "emoji.l"
{yylval.string=strdup("ugh"); return NOUN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "emoji.l"
{yylval.string=strdup("sad"); return NOUN;}
	YY_BREAK
case 35:
#line 46 "emoji.l"
case 36:
#line 47 "emoji.l"
case 37:
#line 48 "emoji.l"
case 38:
YY_RULE_SETUP
#line 48 "emoji.l"
{yylval.string=strdup("happy"); return NOUN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "emoji.l"
{yylval.string=strdup("sick"); return NOUN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "emoji.l"
{yylval.string=strdup("hot"); return NOUN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "emoji.l"
{yylval.string=strdup("cold"); return NOUN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 53 "emoji.l"
{yylval.string=strdup("cool"); return NOUN;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 54 "emoji.l"
{yylval.string=strdup("free"); return NOUN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 55 "emoji.l"
{yylval.string=strdup("ID"); return NOUN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 56 "emoji.l"
{yylval.string=strdup("SOS"); return NOUN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 57 "emoji.l"
{yylval.string=strdup("new"); return NOUN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 58 "emoji.l"
{yylval.string=strdup("A"); return NOUN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 59 "emoji.l"
{yylval.string=strdup("B"); return NOUN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 60 "emoji.l"
{yylval.string=strdup("AB"); return NOUN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 61 "emoji.l"
{yylval.string=strdup("CL"); return NOUN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "emoji.l"
{yylval.string=strdup("abc"); return NOUN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 63 "emoji.l"
{yylval.string=strdup("i"); return NOUN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 64 "emoji.l"
{yylval.string=strdup("OK"); return NOUN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 65 "emoji.l"
{yylval.string=strdup("P"); return NOUN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 66 "emoji.l"
{yylval.string=strdup("VS"); return NOUN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 67 "emoji.l"
{yylval.string=strdup("back"); return NOUN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 68 "emoji.l"
{yylval.string=strdup("end"); return NOUN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 69 "emoji.l"
{yylval.string=strdup("on"); return NOUN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 70 "emoji.l"
{yylval.string=strdup("soon"); return NOUN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "emoji.l"
{yylval.string=strdup("top"); return NOUN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 72 "emoji.l"
{yylval.string=strdup("up"); return NOUN;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "emoji.l"
{yylval.string=strdup("play"); return VERB;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "emoji.l"
{yylval.string=strdup("repeat"); return NOUN;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "emoji.l"
{yylval.string=strdup("pause"); return NOUN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "emoji.l"
{yylval.string=strdup("stop"); return VERB;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "emoji.l"
{yylval.string=strdup("random"); return NOUN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "emoji.l"
{return NOT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "emoji.l"
{yylval.string=strdup("and"); return NOUN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "emoji.l"
{yylval.string=strdup("eggplant"); return NOUN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "emoji.l"
{yylval.string=strdup("avocado"); return NOUN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 84 "emoji.l"
{yylval.string=strdup("potato"); return NOUN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "emoji.l"
{yylval.string=strdup("cucumber"); return NOUN;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 86 "emoji.l"
{yylval.string=strdup("onion"); return NOUN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 87 "emoji.l"
{yylval.string=strdup("garlic"); return NOUN;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 88 "emoji.l"
{yylval.string=strdup("mushroom"); return NOUN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 89 "emoji.l"
{yylval.string=strdup("cabbage"); return NOUN;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "emoji.l"
{yylval.string=strdup("bread"); return NOUN;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "emoji.l"
{yylval.string=strdup("pretzel"); return NOUN;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "emoji.l"
{yylval.string=strdup("pancakes"); return NOUN;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "emoji.l"
{yylval.string=strdup("waffle"); return NOUN;}
	YY_BREAK
case 81:
#line 96 "emoji.l"
case 82:
#line 97 "emoji.l"
case 83:
YY_RULE_SETUP
#line 97 "emoji.l"
{yylval.string=strdup("meat"); return NOUN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 98 "emoji.l"
{yylval.string=strdup("bacon"); return NOUN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 99 "emoji.l"
{yylval.string=strdup("hamburger"); return NOUN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 100 "emoji.l"
{yylval.string=strdup("french fries"); return NOUN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 101 "emoji.l"
{yylval.string=strdup("pizza"); return NOUN;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 102 "emoji.l"
{yylval.string=strdup("hot dog"); return NOUN;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 103 "emoji.l"
{yylval.string=strdup("sandwich"); return NOUN;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 104 "emoji.l"
{yylval.string=strdup("taco"); return NOUN;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 105 "emoji.l"
{yylval.string=strdup("burrito"); return NOUN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 106 "emoji.l"
{yylval.string=strdup("salad"); return NOUN;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 107 "emoji.l"
{yylval.string=strdup("popcorn"); return NOUN;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 109 "emoji.l"
{yylval.string=strdup("egg"); return NOUN;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 110 "emoji.l"
{yylval.string=strdup("cooking"); return NOUN;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 111 "emoji.l"
{yylval.string=strdup("butter"); return NOUN;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 112 "emoji.l"
{yylval.string=strdup("salt"); return NOUN;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 113 "emoji.l"
{yylval.string=strdup("can"); return NOUN;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 115 "emoji.l"
{yylval.string=strdup("circle"); return NOUN;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 116 "emoji.l"
{yylval.string=strdup("square"); return NOUN;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 117 "emoji.l"
{yylval.string=strdup("triangle"); return NOUN;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 118 "emoji.l"
{yylval.string=strdup("diamond"); return NOUN;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 119 "emoji.l"
{yylval.string=strdup("heart"); return HEART;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 121 "emoji.l"
{yylval.string=strdup("hi"); return NOUN;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 122 "emoji.l"
{yylval.string=strdup("perfect"); return NOUN;}
	YY_BREAK
case 106:
#line 124 "emoji.l"
case 107:
YY_RULE_SETUP
#line 124 "emoji.l"
{yylval.string=strdup("left"); return NOUN;}
	YY_BREAK
case 108:
#line 126 "emoji.l"
case 109:
YY_RULE_SETUP
#line 126 "emoji.l"
{yylval.string=strdup("right"); return NOUN;}
	YY_BREAK
case 110:
#line 128 "emoji.l"
case 111:
YY_RULE_SETUP
#line 128 "emoji.l"
{yylval.string=strdup("up"); return NOUN;}
	YY_BREAK
case 112:
#line 130 "emoji.l"
case 113:
YY_RULE_SETUP
#line 130 "emoji.l"
{yylval.string=strdup("down"); return NOUN;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 131 "emoji.l"
{yylval.string=strdup("good"); return NOUN;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 132 "emoji.l"
{yylval.string=strdup("bad"); return NOUN;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 134 "emoji.l"
{yylval.string=strdup("pretty"); return NOUN;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 135 "emoji.l"
{yylval.string=strdup("find"); return VERB;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 136 "emoji.l"
{yylval.string=strdup("game"); return NOUN;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 137 "emoji.l"
{yylval.string=strdup("student"); return NOUN;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 138 "emoji.l"
{yylval.string=strdup("write"); return VERB;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 139 "emoji.l"
{yylval.string=strdup("work"); return VERB;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 140 "emoji.l"
{yylval.string=strdup("speech"); return NOUN;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 141 "emoji.l"
{yylval.string=strdup("jump"); return NOUN;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 142 "emoji.l"
{yylval.string=strdup("time"); return NOUN;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 143 "emoji.l"
{yylval.string=strdup("religion"); return NOUN;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 144 "emoji.l"
{yylval.string=strdup("drink"); return NOUN;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 145 "emoji.l"
{yylval.string=strdup("labor"); return NOUN;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 146 "emoji.l"
{yylval.string=strdup("dance"); return VERB;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 147 "emoji.l"
{yylval.string=strdup("act"); return NOUN;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 148 "emoji.l"
{yylval.string=strdup("volcano"); return NOUN;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 149 "emoji.l"
{yylval.string=strdup("hug"); return NOUN;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 150 "emoji.l"
{yylval.string=strdup("meeting"); return NOUN;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 151 "emoji.l"
{yylval.string=strdup("cow"); return NOUN;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 152 "emoji.l"
{yylval.string=strdup("telephone"); return NOUN;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 153 "emoji.l"
{yylval.string=strdup("ice cream"); return NOUN;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 154 "emoji.l"
{yylval.string=strdup("wool"); return NOUN;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 155 "emoji.l"
{yylval.string=strdup("suit"); return NOUN;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 156 "emoji.l"
{yylval.string=strdup("snake"); return NOUN;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 157 "emoji.l"
{yylval.string=strdup("duck"); return NOUN;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 158 "emoji.l"
{yylval.string=strdup("camera"); return NOUN;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 159 "emoji.l"
{yylval.string=strdup("wait"); return WAIT;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 160 "emoji.l"
{yylval.string=strdup("see"); return VERB;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 161 "emoji.l"
{yylval.string=strdup("swim"); return VERB;}
	YY_BREAK
case 144:
#line 163 "emoji.l"
case 145:
YY_RULE_SETUP
#line 163 "emoji.l"
{yylval.string=strdup("music"); return NOUN;}
	YY_BREAK
case 146:
#line 165 "emoji.l"
case 147:
#line 166 "emoji.l"
case 148:
YY_RULE_SETUP
#line 166 "emoji.l"
{yylval.string=strdup("world"); return NOUN;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 167 "emoji.l"
{yylval.string=strdup("beach"); return NOUN;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 168 "emoji.l"
{yylval.string=strdup("house"); return NOUN;}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 169 "emoji.l"
{yylval.string=strdup("travel"); return VERB;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 170 "emoji.l"
{yylval.string=strdup("rocket"); return NOUN;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 171 "emoji.l"
{yylval.string=strdup("idea"); return NOUN;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 172 "emoji.l"
{yylval.string=strdup("!"); return NOUN;}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 173 "emoji.l"
{yylval.string=strdup("?"); return NOUN;}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 174 "emoji.l"
{yylval.string=strdup("movies"); return NOUN;}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 175 "emoji.l"
{yylval.string=strdup("swear"); return VERB;}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 176 "emoji.l"
{yylval.string=strdup("hate"); return HATE;}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 177 "emoji.l"
{yylval.string=strdup("run"); return VERB;}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 179 "emoji.l"
{yylval.string=strdup("too"); return NOUN;}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 180 "emoji.l"
{yylval.string=strdup("for"); return NOUN;}
	YY_BREAK
case 162:
/* rule 162 can match eol */
YY_RULE_SETUP
#line 182 "emoji.l"
{yylval.string=strdup(yytext); return NOUN;}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 183 "emoji.l"
ECHO;
	YY_BREAK
#line 1677 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 290);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 183 "emoji.l"

